/**
 * Shift Close Report – A4 print via new window (same pattern as bookingSlipPrint.js).
 * Builds HTML document, opens in popup, triggers print on load.
 * @param {Array} bookings - List of consignment/booking objects
 * @param {object} options - { batchCode, copyType, preparedBy, stationCode?, date?, logoUrl? }
 */
export function printShiftCloseReport(bookings = [], options = {}) {
  const list = Array.isArray(bookings) ? bookings : []
  const batchCode = options.batchCode ?? '—'
  const copyType = options.copyType ?? 'OFFICIAL SHIPPING SUMMARY'
  const preparedBy = options.preparedBy ?? '—'
  const stationCode = options.stationCode ?? null
  const reportDate = options.date ? new Date(options.date) : new Date()
  const dateStr = reportDate.toLocaleDateString()
  const logoUrl = options.logoUrl ?? '/nps-logo.png'

  const totalPcs = list.reduce((s, b) => s + (parseInt(b.pieces, 10) || 0), 0)
  const totalWt = list.reduce((s, b) => {
    const w = b.weight != null
      ? (typeof b.weight === 'object' && b.weight !== null && typeof b.weight.toString === 'function'
        ? parseFloat(b.weight.toString())
        : parseFloat(b.weight))
      : 0
    return s + (Number.isFinite(w) ? w : 0)
  }, 0)
  const totalAmt = list.reduce((s, b) => s + (parseFloat(b.totalAmount) || 0), 0)

  const row = (b, i) => {
    const originName = b.originCity?.cityName || b.originCity?.name || b.originCityId || '—'
    const destName = b.destinationCity?.cityName || b.destinationCity?.name || b.destinationCityId || '—'
    const payMode = b.paymentMode || b.payMode || '—'
    const status = b.status || '—'
    const w = b.weight != null
      ? (typeof b.weight === 'object' && b.weight !== null && typeof b.weight.toString === 'function'
        ? parseFloat(b.weight.toString())
        : parseFloat(b.weight))
      : 0
    const isVoided = String(status).toUpperCase() === 'VOIDED'
    return `
    <tr class="${isVoided ? 'sc-voided' : ''}">
      <td class="sc-td sc-td-num">${i + 1}</td>
      <td class="sc-td sc-td-cn">${escapeHtml(b.cnNumber || '—')}</td>
      <td class="sc-td sc-td-center">${escapeHtml(originName)}</td>
      <td class="sc-td sc-td-center">${escapeHtml(destName)}</td>
      <td class="sc-td">
        <div class="sc-party-name">${escapeHtml(b.shipperName || '—')}</div>
        <div class="sc-party-sub">${escapeHtml(b.shipperPhone || '')}</div>
      </td>
      <td class="sc-td">
        <div class="sc-party-name">${escapeHtml(b.consigneeName || '—')}</div>
        <div class="sc-party-sub">${escapeHtml(b.consigneePhone || '')}</div>
      </td>
      <td class="sc-td sc-td-center sc-status">${escapeHtml(status)}</td>
      <td class="sc-td sc-td-center">${escapeHtml(String(payMode).toLowerCase())}</td>
      <td class="sc-td sc-td-center">${escapeHtml(b.pieces ?? '—')} / ${Number.isFinite(w) ? w : (b.weight ?? '—')}</td>
      <td class="sc-td sc-td-right">RS. ${b.totalAmount != null ? Number(b.totalAmount).toLocaleString() : '—'}</td>
    </tr>`
  }

  const metaBlock = stationCode != null
    ? `
      <p>STATION: <span class="sc-meta-val">${escapeHtml(stationCode)}</span></p>
      <p>DATE: ${escapeHtml(dateStr)}</p>
      <p>GENERATED BY: <span class="sc-meta-val">${escapeHtml(preparedBy)}</span></p>`
    : `
      <p>PREPARED BY: <span class="sc-meta-val">${escapeHtml(preparedBy)}</span></p>
      <p>DATE: ${escapeHtml(dateStr)}</p>`

  const signatureBlock = stationCode != null
    ? `
    <div class="sc-signatures">
      <div class="sc-sig-block">
        <div class="sc-sig-line"></div>
        <p class="sc-sig-label">Prepared By (${escapeHtml(preparedBy)})</p>
        <p class="sc-sig-sub">Courier Staff Signature</p>
      </div>
      <div class="sc-sig-block">
        <div class="sc-sig-line"></div>
        <p class="sc-sig-label">Authorized Signature &amp; Stamp</p>
        <p class="sc-sig-sub">Station Manager</p>
      </div>
    </div>`
    : ''

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Shift Closure Report - ${escapeHtml(batchCode)}</title>
  <style>
    @page { size: A4 portrait; margin: 12mm; }
    * { box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; padding: 0; color: #111; font-size: 11px; line-height: 1.4; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .sc-page { width: 210mm; min-height: 297mm; padding: 12mm; margin: 0 auto; }
    .sc-header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 16px; }
    .sc-header-left { display: flex; align-items: center; gap: 12px; }
    .sc-logo { height: 56px; width: auto; display: block; }
    .sc-title { font-size: 20px; font-weight: 900; text-transform: uppercase; }
    .sc-copy-type { font-size: 10px; font-weight: 700; color: #444; letter-spacing: 0.1em; }
    .sc-header-right { text-align: right; }
    .sc-batch { font-size: 18px; font-weight: 900; color: #0c4a6e; }
    .sc-meta { font-size: 10px; margin-top: 4px; }
    .sc-meta-val { font-weight: 900; }
    .sc-table { width: 100%; border-collapse: collapse; border: 1px solid #000; margin-bottom: 16px; }
    .sc-table th, .sc-table td { border: 1px solid #000; padding: 6px 8px; vertical-align: top; }
    .sc-thead { background: #f3f4f6; font-size: 9px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.05em; }
    .sc-td { font-size: 9px; }
    .sc-td-num { text-align: center; }
    .sc-td-cn { font-weight: 900; color: #0c4a6e; }
    .sc-td-center { text-align: center; }
    .sc-td-right { text-align: right; }
    .sc-party-name { font-weight: 700; font-size: 9px; }
    .sc-party-sub { font-size: 8px; color: #555; }
    .sc-status { font-weight: 700; text-transform: uppercase; font-size: 8px; }
    .sc-voided { background: #fef2f2 !important; }
    .sc-tfoot { background: #f9fafb; font-weight: 900; font-size: 10px; }
    .sc-tfoot td { padding: 8px; }
    .sc-signatures { display: grid; grid-template-columns: 1fr 1fr; gap: 48px; margin-top: 32px; padding: 0 24px; }
    .sc-sig-block { text-align: center; }
    .sc-sig-line { border-top: 1px solid #000; padding-top: 8px; margin-bottom: 4px; }
    .sc-sig-label { font-size: 10px; font-weight: 900; text-transform: uppercase; }
    .sc-sig-sub { font-size: 8px; color: #555; font-style: italic; margin-top: 2px; }
    .sc-footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 8px; color: #6b7280; display: flex; justify-content: space-between; text-transform: uppercase; font-weight: 700; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .sc-page { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="sc-page">
    <div class="sc-header">
      <div class="sc-header-left">
        <img src="${escapeHtml(logoUrl)}" alt="NPS Logo" class="sc-logo" />
        <div>
          <h1 class="sc-title">Shift Closure Report</h1>
          <p class="sc-copy-type">${escapeHtml(copyType)}</p>
        </div>
      </div>
      <div class="sc-header-right">
        <div class="sc-batch">BATCH: ${escapeHtml(batchCode)}</div>
        <div class="sc-meta">${metaBlock}</div>
      </div>
    </div>

    <table class="sc-table">
      <thead>
        <tr class="sc-thead">
          <th style="width:3%">SR</th>
          <th style="width:12%">CN NUMBER</th>
          <th style="width:8%">ORIGIN</th>
          <th style="width:8%">DEST</th>
          <th style="width:15%">SHIPPER</th>
          <th style="width:15%">CONSIGNEE</th>
          <th style="width:6%">STATUS</th>
          <th style="width:6%">MODE</th>
          <th style="width:10%">PCS/WGT</th>
          <th style="width:10%">AMOUNT</th>
        </tr>
      </thead>
      <tbody>
        ${list.map((b, i) => row(b, i)).join('')}
      </tbody>
      <tfoot>
        <tr class="sc-tfoot">
          <td colspan="8" style="text-align:right; text-transform:uppercase; letter-spacing:0.05em;">Shift Total Summary</td>
          <td style="text-align:center;">${totalPcs} PCS / ${totalWt.toFixed(2)} KG</td>
          <td style="text-align:right;">RS. ${totalAmt.toLocaleString()}</td>
        </tr>
      </tfoot>
    </table>
    ${signatureBlock}
    <div class="sc-footer">
      <span>Printed on: ${new Date().toLocaleString()}</span>
      <span>Helpline: 0335-2721975 | Shift Close Summary - NPS Courier</span>
    </div>
  </div>
  <script>
    (function() {
      function doPrint() { window.print(); }
      if (document.readyState === 'complete') doPrint();
      else window.addEventListener('load', doPrint);
    })();
  </script>
</body>
</html>`

  const win = window.open('', '_blank')
  if (!win) {
    console.warn('Popup blocked: allow popups to print shift close report.')
    return false
  }
  win.document.write(html)
  win.document.close()
  win.focus()
  return true
}

function escapeHtml(str) {
  if (str == null) return ''
  const s = String(str)
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
