export const metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
}

import './globals.css'
import ReduxProvider from './lib/ReduxProvider'

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className="overflow-x-hidden">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}

